language: python
python:
  - 3
install:
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
script:
 - mypy --ignore-missing-imports little_boxes
 - flake8 little_boxes
 - black --check .
 - python -m pytest -vv --cov=little_boxes
 - codecov
